config/routes.rb
Rails.application.routes.draw do
  resources :product_items

end

app/models/product_item.rb
class ProductItem < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/product_items_controller.rb
class ProductItemsController < ApplicationController
  before_action :set_product_item, only: [:show, :edit, :update, :destroy]

  # GET /product_items
  # GET /product_items.json
  def index
    @product_items = ProductItem.all
  end

  # GET /product_items/1
  # GET /product_items/1.json
  def show
  end

  # GET /product_items/new
  def new
    @product_item = ProductItem.new
  end

  # GET /product_items/1/edit
  def edit
  end

  # POST /product_items
  # POST /product_items.json
  def create
    @product_item = ProductItem.new(product_item_params)

    respond_to do |format|
      if @product_item.save
        format.html { redirect_to @product_item, notice: 'Product item was successfully created.' }
        format.json { render :show, status: :created, location: @product_item }
      else
        format.html { render :new }
        format.json { render json: @product_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_items/1
  # PATCH/PUT /product_items/1.json
  def update
    respond_to do |format|
      if @product_item.update(product_item_params)
        format.html { redirect_to @product_item, notice: 'Product item was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_item }
      else
        format.html { render :edit }
        format.json { render json: @product_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_items/1
  # DELETE /product_items/1.json
  def destroy
    @product_item.destroy
    respond_to do |format|
      format.html { redirect_to product_items_url, notice: 'Product item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_item
      @product_item = ProductItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_item_params
      params.require(:product_item).permit(:product_name, :description, :qty, :msrp)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_items_helper.rb
module ProductItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProductApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/product_items/_form.html.erb
<%= form_for(@product_item) do |f| %>
  <% if @product_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_item.errors.count, "error") %> prohibited this product_item from being saved:</h2>

      <ul>
      <% @product_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

      <div class="field">
        <%= f.label :product_name %><br>
        <%= f.text_field :product_name %>
      </div>
      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_field :description %>
      </div>
      <div class="field">
        <%= f.label :qty %><br>
        <%= f.text_field :qty %>
      </div>
      <div class="field">
        <%= f.label :msrp %><br>
        <%= f.text_field :msrp %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    
<% end %>

app/views/product_items/edit.html.erb
<body class="homepage">

	<div class="col-md-12 col-md-offset-4">
	    <div class="product-container">

			<h1>Editing Product Item</h1>

			<%= render 'form' %>

			<%= link_to 'Show', @product_item %> |
			<%= link_to 'Back', product_items_path %>

		</div>
	</div>

</body>

app/views/product_items/index.html.erb
<p id="notice"><%= notice %></p>

<body class="homepage">

  <div class="col-md-12 col-md-offset-4">
    
    <img src="/assets/wl_logo_white.png" alt="digitouch" class="wl" />

  </div>

  <div class="col-md-12 col-md-offset-1">

    <div class="panel-default">

    <div class="panel-heading"><h1>List of Product Items</h1></div>

    <table class="table">
      <thead>
        <tr>
          <th>Product Name</th>
          <th>Description</th>
          <th>Qty Arrived</th>
          <th>MSRP</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @product_items.each do |product_item| %>
          <tr>
            <td><%= product_item.product_name %></td>
            <td><%= product_item.description %></td>
            <td><%= product_item.qty %></td>
            <td><%= product_item.msrp %></td>
            <td><%= link_to 'Show', product_item %></td>
            <td><%= link_to 'Edit', edit_product_item_path(product_item) %></td>
            <td><%= link_to 'Destroy', product_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Product item', new_product_item_path, class: 'btn btn-primary' %>

    </div>
  </div>

</body>

app/views/product_items/new.html.erb
<body class="homepage">	

	<div class="col-md-12 col-md-offset-4">
	    <div class="product-container">

			<h1>New Product Item</h1>

			<%= render 'form' %>

			<%= link_to 'Back', product_items_path %>
		</div>
	</div>

</body>

app/views/product_items/show.html.erb
<p id="notice"><%= notice %></p>
  
  <body class="homepage">

    <div class="col-md-12 col-md-offset-4">
      <div class="product-container">
         
       <p class="text-center">
         <strong>Product Name:</strong>
         <%= @product_item.product_name %>
       </p>
       
       <p class="text-center">
         <strong>Description:</strong>
         <%= @product_item.description %>
       </p>

       <p class="text-center">
         <strong>Qty Arrived:</strong>
         <%= @product_item.qty %>
       </p>

       <p class="text-center">
         <strong>MSRP:</strong>
         <%= @product_item.msrp %>
       </p>

      </div>

      <div class="col-md-4">
        <%= link_to 'Edit', edit_product_item_path(@product_item) %> |
        <%= link_to 'Back', product_items_path %>
      </div>
    </div>

  </body>